# -*- coding: utf-8 -*-
"""A3 - Basic Operations .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ey31R1TP_3zfMhIpCQgSp16PSFz56cRq
"""

import  matplotlib.pyplot  as  plt 
import  numpy  as  np 

universe=np.arange(0,10.1,0.1)
A=[]
B=[]
C=[]
AuB=[]
AuC=[]
BuC=[]
AnB=[]
AnC=[]
BnC=[]
cA=[]
cB=[]
cC=[]

for i in universe:
    A.append(i/(i+2))
    B.append(2**(-i))
    C.append(1/(1+10*((i-2)**2)))  

for k in range(len(universe)):
  AuB.append(max(A[k],B[k]))  
  AuC.append(max(A[k],C[k]))
  BuC.append(max(B[k],C[k]))
  AnB.append(min(A[k],B[k]))
  AnC.append(min(A[k],C[k]))
  BnC.append(min(B[k],C[k]))
  cA.append(1-A[k])
  cB.append(1-B[k])
  cC.append(1-C[k])

fig=plt.figure(figsize=(10,10),tight_layout=True)
fig.supylabel('Membership Degree')
fig.suptitle("Basic Fuzzy Operations")

plt.subplot(3,3,1)
plt.plot(universe,A,'--r',universe,B,'--g',universe,AuB,'y')
plt.title("A u B")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(3,3,2)
plt.plot(universe,A,'--r',universe,C,'--k',universe,AuC,'y')
plt.title("A u C")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(3,3,3)
plt.plot(universe,B,'--g',universe,C,'--k',universe,BuC,'y')
plt.title("B u C")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(3,3,4)
plt.plot(universe,A,'--r',universe,B,'--g',universe,AnB,'y')
plt.title("A n B")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(3,3,5)
plt.plot(universe,A,'--r',universe,C,'--k',universe,AnC,'y')
plt.title("A n C")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(3,3,6)
plt.plot(universe,B,'--g',universe,C,'--k',universe,BnC,'y')
plt.title("B n C")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(3,3,7)
plt.plot(universe,A,'--r',universe,cA,'y')
plt.title("Complement of A")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(3,3,8)
plt.plot(universe,B,'--g',universe,cB,'y')
plt.title("Complement of B")
plt.xlabel("Universe")
plt.grid(True)

plt.subplot(3,3,9)
plt.plot(universe,C,'--k',universe,cC,'y')
plt.title("Complement of C")
plt.xlabel("Universe")
plt.grid(True)

