# -*- coding: utf-8 -*-
"""A7 MaxMinAndMaxProd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_RLThwDDktNZ_7ldlhV120ez4PNHXnzF
"""

#Calculate the Max-min and Max-Prod 

def prod(a,b):
  return a*b

X1oZ1=max(min(0.5,1),min(0.1,0.4),min(0.7,0.8))
X1oZ2=max(min(0.5,0.6),min(0.1,0.3),min(0.7,0.8))
X1oZ3=max(min(0.5,1),min(0.1,0.8),min(0.7,0.2))

X2oZ1=max(min(0.3,1),min(0.5,0.4),min(0.8,0.8))
X2oZ2=max(min(0.3,0.6),min(0.5,0.3),min(0.8,0.8))
X2oZ3=max(min(0.3,1),min(0.5,0.8),min(0.8,0.2))

R1oR2=[[X1oZ1,X1oZ2,X1oZ3],[X2oZ1,X2oZ2,X2oZ3]]


X1xZ1=max(prod(0.5,1),prod(0.1,0.4),prod(0.7,0.8))
X1xZ2=max(prod(0.5,0.6),prod(0.1,0.3),prod(0.7,0.8))
X1xZ3=max(prod(0.5,1),prod(0.1,0.8),prod(0.7,0.2))

X2xZ1=max(prod(0.3,1),prod(0.5,0.4),prod(0.8,0.8))
X2xZ2=max(prod(0.3,0.6),prod(0.5,0.3),prod(0.8,0.8))
X2xZ3=max(prod(0.3,1),prod(0.5,0.8),prod(0.8,0.2))

R1xR2=[[X1xZ1,X1xZ2,X1xZ3],[X2xZ1,X2xZ2,X2xZ3]]

print("Max-Min")
print(R1oR2[0])
print(R1oR2[1])

print("\n")
print("Max-Prod")
print(R1xR2[0])
print(R1xR2[1])